<?php

return [
    [
        'key' => 'general.design.nebula_theme',
        'name' => 'nc::app.configuration.title',
        'info' => 'nc::app.configuration.info',
        'sort' => 3,
        'fields' => [
            [
                'name' => 'primary_color',
                'title' => 'nc::app.configuration.primary_color',
                'info' => 'nc::app.configuration.primary_color_info',
                'type' => 'color',
                'default' => '#bd1765',
                'channel_based' => true,
                'locale_based' => false,
            ],
            [
                'name' => 'secondary_color',
                'title' => 'nc::app.configuration.secondary_color',
                'info' => 'nc::app.configuration.secondary_color_info',
                'type' => 'color',
                'default' => '#91e4d9',
                'channel_based' => true,
                'locale_based' => false,
            ],
            [
                'name' => 'font_arabic',
                'title' => 'nc::app.configuration.font_arabic',
                'info' => 'nc::app.configuration.font_arabic_info',
                'type' => 'select',
                'default' => 'Tajawal',
                'channel_based' => true,
                'locale_based' => false,
                'options' => [
                    ['title' => 'Tajawal (تجوال - الأساس الافتراضي)', 'value' => 'Tajawal'],
                    ['title' => 'Cairo (القاهرة - هندسي حديث)', 'value' => 'Cairo'],
                    ['title' => 'Alexandria (الإسكندرية - فاخر وعصري)', 'value' => 'Alexandria'],
                    ['title' => 'IBM Plex Sans Arabic (آي بي إم بلكس - تقني وأنيق)', 'value' => 'IBM Plex Sans Arabic'],
                    ['title' => 'Readex Pro (ريديكس برو)', 'value' => 'Readex Pro'],
                    ['title' => 'El Messiri (المسيري - جمالي فاخر)', 'value' => 'El Messiri'],
                    ['title' => 'Amiri (أميري - كلاسيكي شرقي)', 'value' => 'Amiri'],
                    ['title' => 'Almarai (المراعي)', 'value' => 'Almarai'],
                    ['title' => 'Noto Sans Arabic (نوتو سانز عربي)', 'value' => 'Noto Sans Arabic'],
                    ['title' => 'Marhey (مرحي - عصري وجذاب)', 'value' => 'Marhey'],
                    ['title' => 'Changa (تشانجا)', 'value' => 'Changa'],
                    ['title' => 'Aref Ruqaa (عارف رقعة)', 'value' => 'Aref Ruqaa'],
                    ['title' => 'Reem Kufi (ريم كوفي)', 'value' => 'Reem Kufi'],
                    ['title' => 'Rubik (روبيك)', 'value' => 'Rubik'],
                    ['title' => 'Mada (مدى)', 'value' => 'Mada'],
                    ['title' => 'Lemonada (ليمونادة)', 'value' => 'Lemonada'],
                    ['title' => 'Scheherazade New (شهرزاد)', 'value' => 'Scheherazade New'],
                ],
            ],
            [
                'name' => 'custom_font_arabic',
                'title' => 'nc::app.configuration.custom_font_arabic',
                'info' => 'nc::app.configuration.custom_font_arabic_info',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => false,
            ],
            [
                'name' => 'font_english',
                'title' => 'nc::app.configuration.font_english',
                'info' => 'nc::app.configuration.font_english_info',
                'type' => 'select',
                'default' => 'Cormorant Garamond',
                'channel_based' => true,
                'locale_based' => false,
                'options' => [
                    ['title' => 'Cormorant Garamond (Editorial Luxury Serif)', 'value' => 'Cormorant Garamond'],
                    ['title' => 'Plus Jakarta Sans (Modern Clean)', 'value' => 'Plus Jakarta Sans'],
                    ['title' => 'DM Sans (Contemporary Clean)', 'value' => 'DM Sans'],
                    ['title' => 'Playfair Display (Luxury High-End Serif)', 'value' => 'Playfair Display'],
                    ['title' => 'Inter (Modern Minimal)', 'value' => 'Inter'],
                    ['title' => 'Courier Prime (Editorial Monospace)', 'value' => 'Courier Prime'],
                    ['title' => 'Montserrat (Bold Modern)', 'value' => 'Montserrat'],
                    ['title' => 'Poppins (Geometric Modern)', 'value' => 'Poppins'],
                    ['title' => 'Lato (Warm Sans)', 'value' => 'Lato'],
                    ['title' => 'Roboto (Balanced Sans)', 'value' => 'Roboto'],
                    ['title' => 'Raleway (Refined Sans)', 'value' => 'Raleway'],
                    ['title' => 'Bodoni Moda (High Fashion)', 'value' => 'Bodoni Moda'],
                    ['title' => 'Cinzel (Classical Luxury)', 'value' => 'Cinzel'],
                    ['title' => 'Prata (Fashion Editorial)', 'value' => 'Prata'],
                    ['title' => 'Oswald (Condensed Impact)', 'value' => 'Oswald'],
                ],
            ],
            [
                'name' => 'custom_font_english',
                'title' => 'nc::app.configuration.custom_font_english',
                'info' => 'nc::app.configuration.custom_font_english_info',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => false,
            ],
            [
                'name' => 'cleo_lab_seeder',
                'title' => 'nc::app.configuration.seeder_title',
                'type' => 'blade',
                'path' => 'nc::configuration.custom-views.cleo-lab-seeder',
            ],
        ],
    ],
];
